import math

# GAME SETTINGS
WIDTH, HEIGHT = 1600, 900

RES = (WIDTH, HEIGHT)
FPS = 0

PLAYER_INITIAL_POS = 1.5, 5  # mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

# RAY CASTING
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
# draw distance
MAX_DEPTH = 20

# RAY CASTING 3D PROJECTION
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
SCREEN_DIS = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS
