import math

# GAME SETTINGS
SCREEN_WIDTH, SCREEN_HEIGHT = 1600, 900

RES = (SCREEN_WIDTH, SCREEN_HEIGHT)
FPS = 0

PLAYER_INITIAL_POS = 1.5, 5  # mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

# RAY CASTING
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = SCREEN_WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
# draw distance
MAX_DEPTH = 20

# RAY CASTING 3D PROJECTION
HALF_WIDTH = SCREEN_WIDTH // 2
HALF_HEIGHT = SCREEN_HEIGHT // 2
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = SCREEN_WIDTH // NUM_RAYS

# TEXTURES RELATED
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
